import {
  BadgeCheck,
  Briefcase,
  Building2,
  FolderKanban,
  Inbox,
  LayoutDashboard,
  LineChart,
  Link2,
  ListChecks,
  Package,
  Settings,
  Shield,
  Tags,
  UserRound,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

export const NAV_ICONS: Record<string, LucideIcon> = {
  "adv.overview": LayoutDashboard,
  "adv.profile": UserRound,
  "adv.kyc": Shield,
  "adv.posts": ListChecks,
  "adv.creators": Users,
  "adv.briefs": Briefcase,
  "adv.wallet": Wallet,
  "adv.inbox": Inbox,
  "adv.analytics": LineChart,
  "cre.overview": LayoutDashboard,
  "cre.briefs": Briefcase,
  "cre.packages": Package,
  "cre.profile": UserRound,
  "cre.kyc": Shield,
  "cre.codes": Link2,
  "cre.earnings": Wallet,
  "cre.claim": BadgeCheck,
  "adm.overview": LayoutDashboard,
  "adm.pages": FolderKanban,
  "adm.creators": Users,
  "adm.advertisers": Building2,
  "adm.kyc": Shield,
  "adm.categories": Tags,
  "adm.settings": Settings,
  "adm.users": Users,
  "adm.balances": Wallet,
  "adm.payments": ListChecks,
  "adm.audit": LineChart,
};
